### ISSUE TITLE
Cannot manipulate dom elements

### ISSUE THREAD

**Issue by cg923** [Astroknut/Project3#12]
Hi guys.

I am totally stuck.  I have an ngFor directive that builds a certain number of divs based on the number of items in an array.

To be specific, in journals.component.html I have:
`<div *ngFor="let journal of journals" [attr.id]="'journal' + journal.id">{{journal.name}}</div>`

And in journals.component.ts, I would like to select a specific one of those (the very first one) and give it a css class.  My code has successfully given each div a unique id based using the `[attr.id]="'Journal' + journal.id"` snippet, but I just cannot figure out how to grab a unique HTML element by ID.

Perhaps I'm going about this the wrong way, but this seems to mostly be a problem of wrapping my head around it, rather than a code sticking point.

Here are some articles I looked at:
https://stackoverflow.com/questions/32693061/angular-2-typescript-get-hold-of-an-element-in-the-template
The problem with this solution ^ is that it assumes my component only has one HTML element (I think)

And approaches like this:
https://stackoverflow.com/questions/41332680/how-i-can-access-dom-element-by-selector
Are discouraged.

I talked to Zeb a little bit about this before and thought I had figured something out, but I just am totally lost right now.

**Comment by ZebGirouard** [comment]
Hm...it seems like you could use `journal.id === 0` (or 1 if that's the first one) with ngClass like you see here:

https://angular.io/api/common/NgClass

This line in particular: `[ngClass]="{'first': true, 'second': true, 'third': false}"` is the syntax you want to use.  Those curly braces wrap several classes: 'first', 'second', 'third'.  They will only apply to an element if the thing after the colon is true.  So rather than `true` or `false`, you can put  `journal.id === 0` after the colon, and your class will only apply for the 0th journal.

Let me know if that doesn't clear things up.

**Comment by cg923** [comment]
Oh wow, I totally didn't realize that was how that worked.  I feel like the documentation does not explain that at all.  I'm not able to get it working exactly at first glance, but I think this is definitely the right track.  Thank you, Zeb!
